import type { NutritionData } from './openfoodfacts';

// Base d'aliments courants francais — valeurs pour 100g
// Source : table Ciqual (ANSES) + valeurs standards reconnues
export const ALIMENTS_BASE: NutritionData[] = [
  // ===== VIANDES & VOLAILLES =====
  { code: 'base-filet-poulet', name: 'Filet de poulet', brand: '', calories: 121, proteines: 26.2, glucides: 0, lipides: 1.8, image_url: null },
  { code: 'base-cuisse-poulet', name: 'Cuisse de poulet', brand: '', calories: 170, proteines: 20, glucides: 0, lipides: 10, image_url: null },
  { code: 'base-poulet-roti', name: 'Poulet rôti', brand: '', calories: 213, proteines: 23, glucides: 0, lipides: 14, image_url: null },
  { code: 'base-escalope-dinde', name: 'Escalope de dinde', brand: '', calories: 108, proteines: 24, glucides: 0, lipides: 1.5, image_url: null },
  { code: 'base-dinde-rotie', name: 'Dinde rôtie', brand: '', calories: 188, proteines: 31, glucides: 0, lipides: 7, image_url: null },
  { code: 'base-magret-canard', name: 'Magret de canard', brand: '', calories: 270, proteines: 23, glucides: 0, lipides: 20, image_url: null },
  { code: 'base-steak-hache-5', name: 'Steak haché 5%', brand: '', calories: 136, proteines: 22, glucides: 0, lipides: 5.5, image_url: null },
  { code: 'base-steak-hache-15', name: 'Steak haché 15%', brand: '', calories: 218, proteines: 19, glucides: 0, lipides: 15, image_url: null },
  { code: 'base-steak-hache-20', name: 'Steak haché 20%', brand: '', calories: 260, proteines: 18, glucides: 0, lipides: 20, image_url: null },
  { code: 'base-entrecote', name: 'Entrecôte de boeuf', brand: '', calories: 208, proteines: 20, glucides: 0, lipides: 14, image_url: null },
  { code: 'base-rosbif', name: 'Rosbif', brand: '', calories: 165, proteines: 28, glucides: 0, lipides: 6, image_url: null },
  { code: 'base-cote-porc', name: 'Côte de porc', brand: '', calories: 207, proteines: 19, glucides: 0, lipides: 14, image_url: null },
  { code: 'base-merguez', name: 'Merguez', brand: '', calories: 280, proteines: 15, glucides: 1, lipides: 24, image_url: null },
  { code: 'base-jambon-blanc', name: 'Jambon blanc', brand: '', calories: 115, proteines: 21, glucides: 1, lipides: 3, image_url: null },
  { code: 'base-jambon-cru', name: 'Jambon cru', brand: '', calories: 246, proteines: 26, glucides: 0.5, lipides: 16, image_url: null },
  { code: 'base-saucisson', name: 'Saucisson sec', brand: '', calories: 460, proteines: 26, glucides: 1, lipides: 39, image_url: null },
  { code: 'base-chorizo', name: 'Chorizo', brand: '', calories: 380, proteines: 22, glucides: 1.5, lipides: 32, image_url: null },
  { code: 'base-bacon', name: 'Bacon', brand: '', calories: 540, proteines: 16, glucides: 0.5, lipides: 50, image_url: null },
  { code: 'base-lardons', name: 'Lardons fumés', brand: '', calories: 260, proteines: 16, glucides: 0.5, lipides: 22, image_url: null },

  // ===== POISSONS & FRUITS DE MER =====
  { code: 'base-saumon', name: 'Saumon frais', brand: '', calories: 208, proteines: 20, glucides: 0, lipides: 13, image_url: null },
  { code: 'base-saumon-fume', name: 'Saumon fumé', brand: '', calories: 180, proteines: 22, glucides: 0, lipides: 10, image_url: null },
  { code: 'base-thon-frais', name: 'Thon frais', brand: '', calories: 130, proteines: 29, glucides: 0, lipides: 1, image_url: null },
  { code: 'base-thon-boite', name: 'Thon en boîte (naturel)', brand: '', calories: 116, proteines: 26, glucides: 0, lipides: 1, image_url: null },
  { code: 'base-cabillaud', name: 'Cabillaud', brand: '', calories: 80, proteines: 18, glucides: 0, lipides: 0.7, image_url: null },
  { code: 'base-truite', name: 'Truite', brand: '', calories: 140, proteines: 20, glucides: 0, lipides: 7, image_url: null },
  { code: 'base-dorade', name: 'Dorade', brand: '', calories: 90, proteines: 19, glucides: 0, lipides: 1.5, image_url: null },
  { code: 'base-bar', name: 'Bar', brand: '', calories: 96, proteines: 19, glucides: 0, lipides: 2, image_url: null },
  { code: 'base-colin', name: 'Colin', brand: '', calories: 78, proteines: 17, glucides: 0, lipides: 1, image_url: null },
  { code: 'base-maquereau', name: 'Maquereau', brand: '', calories: 220, proteines: 19, glucides: 0, lipides: 16, image_url: null },
  { code: 'base-hareng-fume', name: 'Hareng fumé', brand: '', calories: 220, proteines: 22, glucides: 0, lipides: 14, image_url: null },
  { code: 'base-anchois', name: 'Anchois (en boîte)', brand: '', calories: 195, proteines: 20, glucides: 0, lipides: 12, image_url: null },
  { code: 'base-sardines', name: 'Sardines en boîte', brand: '', calories: 220, proteines: 22, glucides: 0, lipides: 14, image_url: null },
  { code: 'base-crevettes', name: 'Crevettes', brand: '', calories: 98, proteines: 21, glucides: 0, lipides: 1.4, image_url: null },
  { code: 'base-moules', name: 'Moules', brand: '', calories: 86, proteines: 12, glucides: 4, lipides: 2, image_url: null },
  { code: 'base-calamars', name: 'Calamars', brand: '', calories: 92, proteines: 16, glucides: 3, lipides: 2, image_url: null },
  { code: 'base-surimi', name: 'Surimi', brand: '', calories: 95, proteines: 11, glucides: 11, lipides: 1, image_url: null },

  // ===== OEUFS =====
  { code: 'base-oeuf', name: 'Oeuf entier (60g)', brand: '', calories: 140, proteines: 12, glucides: 0.7, lipides: 10, image_url: null },
  { code: 'base-blanc-oeuf', name: 'Blanc d\'oeuf', brand: '', calories: 48, proteines: 11, glucides: 0.7, lipides: 0, image_url: null },
  { code: 'base-oeuf-plat', name: 'Oeuf au plat', brand: '', calories: 195, proteines: 13, glucides: 0.5, lipides: 16, image_url: null },
  { code: 'base-oeuf-brouille', name: 'Oeuf brouillé', brand: '', calories: 165, proteines: 11, glucides: 1, lipides: 13, image_url: null },
  { code: 'base-omelette', name: 'Omelette nature', brand: '', calories: 175, proteines: 11, glucides: 1, lipides: 14, image_url: null },

  // ===== PRODUITS LAITIERS =====
  { code: 'base-lait-entier', name: 'Lait entier', brand: '', calories: 64, proteines: 3.2, glucides: 4.7, lipides: 3.5, image_url: null },
  { code: 'base-lait-demi', name: 'Lait demi-écrémé', brand: '', calories: 46, proteines: 3.2, glucides: 4.8, lipides: 1.6, image_url: null },
  { code: 'base-lait-ecreme', name: 'Lait écrémé', brand: '', calories: 33, proteines: 3.3, glucides: 4.9, lipides: 0.1, image_url: null },
  { code: 'base-lait-amande', name: 'Lait d\'amande', brand: '', calories: 24, proteines: 0.5, glucides: 3, lipides: 1, image_url: null },
  { code: 'base-lait-soja', name: 'Lait de soja', brand: '', calories: 47, proteines: 3.6, glucides: 2, lipides: 2, image_url: null },
  { code: 'base-lait-avoine', name: 'Lait d\'avoine', brand: '', calories: 48, proteines: 1, glucides: 7, lipides: 1.5, image_url: null },
  { code: 'base-yaourt-nature', name: 'Yaourt nature', brand: '', calories: 60, proteines: 4, glucides: 5, lipides: 2.5, image_url: null },
  { code: 'base-yaourt-grec', name: 'Yaourt grec', brand: '', calories: 97, proteines: 9, glucides: 4, lipides: 5, image_url: null },
  { code: 'base-yaourt-fruits', name: 'Yaourt aux fruits', brand: '', calories: 85, proteines: 4, glucides: 14, lipides: 1.5, image_url: null },
  { code: 'base-kefir', name: 'Kéfir', brand: '', calories: 55, proteines: 3.3, glucides: 4, lipides: 3, image_url: null },
  { code: 'base-fromage-blanc-0', name: 'Fromage blanc 0%', brand: '', calories: 46, proteines: 8, glucides: 4, lipides: 0, image_url: null },
  { code: 'base-fromage-blanc', name: 'Fromage blanc 3%', brand: '', calories: 68, proteines: 7, glucides: 4, lipides: 3, image_url: null },
  { code: 'base-emmental', name: 'Emmental', brand: '', calories: 370, proteines: 27, glucides: 0, lipides: 29, image_url: null },
  { code: 'base-comte', name: 'Comté', brand: '', calories: 410, proteines: 28, glucides: 0, lipides: 33, image_url: null },
  { code: 'base-camembert', name: 'Camembert', brand: '', calories: 290, proteines: 20, glucides: 0, lipides: 23, image_url: null },
  { code: 'base-brie', name: 'Brie', brand: '', calories: 335, proteines: 21, glucides: 0, lipides: 28, image_url: null },
  { code: 'base-chevre', name: 'Chèvre frais', brand: '', calories: 165, proteines: 12, glucides: 1, lipides: 13, image_url: null },
  { code: 'base-roquefort', name: 'Roquefort', brand: '', calories: 370, proteines: 19, glucides: 0, lipides: 32, image_url: null },
  { code: 'base-reblochon', name: 'Reblochon', brand: '', calories: 330, proteines: 20, glucides: 0, lipides: 27, image_url: null },
  { code: 'base-mozzarella', name: 'Mozzarella', brand: '', calories: 250, proteines: 18, glucides: 1, lipides: 19, image_url: null },
  { code: 'base-parmesan', name: 'Parmesan', brand: '', calories: 415, proteines: 36, glucides: 4, lipides: 28, image_url: null },
  { code: 'base-feta', name: 'Feta', brand: '', calories: 265, proteines: 14, glucides: 1, lipides: 22, image_url: null },
  { code: 'base-ricotta', name: 'Ricotta', brand: '', calories: 155, proteines: 10, glucides: 4, lipides: 12, image_url: null },
  { code: 'base-beurre', name: 'Beurre', brand: '', calories: 745, proteines: 0.8, glucides: 0.5, lipides: 82, image_url: null },
  { code: 'base-creme-fraiche', name: 'Crème fraîche 30%', brand: '', calories: 300, proteines: 2.2, glucides: 3, lipides: 30, image_url: null },

  // ===== FECULENTS & LEGUMINEUSES =====
  { code: 'base-riz-blanc-cuit', name: 'Riz blanc (cuit)', brand: '', calories: 130, proteines: 2.7, glucides: 28, lipides: 0.3, image_url: null },
  { code: 'base-riz-complet-cuit', name: 'Riz complet (cuit)', brand: '', calories: 123, proteines: 2.7, glucides: 25, lipides: 1, image_url: null },
  { code: 'base-riz-basmati', name: 'Riz basmati (cuit)', brand: '', calories: 130, proteines: 2.7, glucides: 28, lipides: 0.3, image_url: null },
  { code: 'base-pates-cuites', name: 'Pâtes (cuites)', brand: '', calories: 131, proteines: 5, glucides: 25, lipides: 0.7, image_url: null },
  { code: 'base-gnocchi', name: 'Gnocchi (cuits)', brand: '', calories: 130, proteines: 3, glucides: 25, lipides: 1, image_url: null },
  { code: 'base-semoule-cuite', name: 'Semoule (cuite)', brand: '', calories: 113, proteines: 4, glucides: 23, lipides: 0.2, image_url: null },
  { code: 'base-boulgour', name: 'Boulgour (cuit)', brand: '', calories: 110, proteines: 4, glucides: 22, lipides: 0.5, image_url: null },
  { code: 'base-quinoa-cuit', name: 'Quinoa (cuit)', brand: '', calories: 120, proteines: 4.4, glucides: 21, lipides: 1.9, image_url: null },
  { code: 'base-polenta', name: 'Polenta (cuite)', brand: '', calories: 76, proteines: 1.7, glucides: 16, lipides: 0.4, image_url: null },
  { code: 'base-sarrasin', name: 'Sarrasin (cuit)', brand: '', calories: 92, proteines: 3.4, glucides: 19, lipides: 0.6, image_url: null },
  { code: 'base-pomme-de-terre', name: 'Pomme de terre (cuite)', brand: '', calories: 80, proteines: 2, glucides: 17, lipides: 0.1, image_url: null },
  { code: 'base-patate-douce', name: 'Patate douce (cuite)', brand: '', calories: 90, proteines: 1.6, glucides: 20, lipides: 0.1, image_url: null },
  { code: 'base-lentilles-cuites', name: 'Lentilles (cuites)', brand: '', calories: 112, proteines: 9, glucides: 16, lipides: 0.4, image_url: null },
  { code: 'base-pois-chiches-cuits', name: 'Pois chiches (cuits)', brand: '', calories: 164, proteines: 9, glucides: 27, lipides: 2.6, image_url: null },
  { code: 'base-haricots-rouges', name: 'Haricots rouges (cuits)', brand: '', calories: 127, proteines: 9, glucides: 22, lipides: 0.5, image_url: null },
  { code: 'base-haricots-blancs', name: 'Haricots blancs (cuits)', brand: '', calories: 120, proteines: 8, glucides: 21, lipides: 0.5, image_url: null },
  { code: 'base-feves', name: 'Fèves (cuites)', brand: '', calories: 100, proteines: 7, glucides: 17, lipides: 0.4, image_url: null },
  { code: 'base-edamame', name: 'Edamame', brand: '', calories: 125, proteines: 11, glucides: 8, lipides: 5, image_url: null },

  // ===== PAIN & BOULANGERIE =====
  { code: 'base-pain-blanc', name: 'Pain blanc (baguette)', brand: '', calories: 265, proteines: 8, glucides: 55, lipides: 1.3, image_url: null },
  { code: 'base-baguette-tradition', name: 'Baguette tradition', brand: '', calories: 270, proteines: 8, glucides: 55, lipides: 1, image_url: null },
  { code: 'base-pain-complet', name: 'Pain complet', brand: '', calories: 247, proteines: 9, glucides: 46, lipides: 2.5, image_url: null },
  { code: 'base-pain-mie', name: 'Pain de mie', brand: '', calories: 275, proteines: 8, glucides: 49, lipides: 4, image_url: null },
  { code: 'base-pain-seigle', name: 'Pain de seigle', brand: '', calories: 220, proteines: 7, glucides: 44, lipides: 1, image_url: null },
  { code: 'base-pain-campagne', name: 'Pain de campagne', brand: '', calories: 250, proteines: 8, glucides: 50, lipides: 1.5, image_url: null },
  { code: 'base-biscotte', name: 'Biscotte', brand: '', calories: 400, proteines: 11, glucides: 75, lipides: 6, image_url: null },
  { code: 'base-croissant', name: 'Croissant', brand: '', calories: 415, proteines: 8, glucides: 45, lipides: 22, image_url: null },
  { code: 'base-pain-chocolat', name: 'Pain au chocolat', brand: '', calories: 415, proteines: 7, glucides: 50, lipides: 21, image_url: null },
  { code: 'base-brioche', name: 'Brioche', brand: '', calories: 360, proteines: 8, glucides: 50, lipides: 14, image_url: null },
  { code: 'base-pain-lait', name: 'Pain au lait', brand: '', calories: 350, proteines: 8, glucides: 55, lipides: 9, image_url: null },
  { code: 'base-crepe', name: 'Crêpe nature', brand: '', calories: 200, proteines: 7, glucides: 33, lipides: 5, image_url: null },
  { code: 'base-gaufre', name: 'Gaufre', brand: '', calories: 290, proteines: 6, glucides: 38, lipides: 13, image_url: null },

  // ===== CEREALES PETIT-DEJEUNER =====
  { code: 'base-flocons-avoine', name: 'Flocons d\'avoine', brand: '', calories: 367, proteines: 14, glucides: 58, lipides: 7, image_url: null },
  { code: 'base-muesli', name: 'Muesli', brand: '', calories: 370, proteines: 10, glucides: 60, lipides: 8, image_url: null },
  { code: 'base-granola', name: 'Granola', brand: '', calories: 460, proteines: 11, glucides: 60, lipides: 18, image_url: null },
  { code: 'base-cornflakes', name: 'Cornflakes', brand: '', calories: 380, proteines: 8, glucides: 84, lipides: 1, image_url: null },
  { code: 'base-special-k', name: 'Special K', brand: '', calories: 380, proteines: 14, glucides: 75, lipides: 2, image_url: null },
  { code: 'base-porridge', name: 'Porridge', brand: '', calories: 70, proteines: 2.5, glucides: 12, lipides: 1.4, image_url: null },

  // ===== FRUITS =====
  { code: 'base-pomme', name: 'Pomme', brand: '', calories: 52, proteines: 0.3, glucides: 12, lipides: 0.2, image_url: null },
  { code: 'base-banane', name: 'Banane', brand: '', calories: 90, proteines: 1.1, glucides: 20, lipides: 0.3, image_url: null },
  { code: 'base-orange', name: 'Orange', brand: '', calories: 47, proteines: 0.9, glucides: 10, lipides: 0.1, image_url: null },
  { code: 'base-clementine', name: 'Clémentine', brand: '', calories: 47, proteines: 0.9, glucides: 10, lipides: 0.2, image_url: null },
  { code: 'base-citron', name: 'Citron', brand: '', calories: 30, proteines: 1, glucides: 6, lipides: 0.2, image_url: null },
  { code: 'base-pamplemousse', name: 'Pamplemousse', brand: '', calories: 40, proteines: 0.7, glucides: 9, lipides: 0.1, image_url: null },
  { code: 'base-poire', name: 'Poire', brand: '', calories: 53, proteines: 0.4, glucides: 12, lipides: 0.1, image_url: null },
  { code: 'base-peche', name: 'Pêche', brand: '', calories: 39, proteines: 0.7, glucides: 8, lipides: 0.3, image_url: null },
  { code: 'base-abricot', name: 'Abricot', brand: '', calories: 48, proteines: 0.9, glucides: 10, lipides: 0.4, image_url: null },
  { code: 'base-prune', name: 'Prune', brand: '', calories: 46, proteines: 0.6, glucides: 10, lipides: 0.3, image_url: null },
  { code: 'base-cerise', name: 'Cerise', brand: '', calories: 63, proteines: 1, glucides: 13, lipides: 0.3, image_url: null },
  { code: 'base-fraises', name: 'Fraises', brand: '', calories: 33, proteines: 0.7, glucides: 6, lipides: 0.3, image_url: null },
  { code: 'base-framboise', name: 'Framboise', brand: '', calories: 43, proteines: 1.1, glucides: 9, lipides: 0.6, image_url: null },
  { code: 'base-myrtille', name: 'Myrtille', brand: '', calories: 53, proteines: 0.7, glucides: 12, lipides: 0.3, image_url: null },
  { code: 'base-raisin', name: 'Raisin', brand: '', calories: 72, proteines: 0.6, glucides: 16, lipides: 0.2, image_url: null },
  { code: 'base-melon', name: 'Melon', brand: '', calories: 34, proteines: 0.8, glucides: 7.5, lipides: 0.2, image_url: null },
  { code: 'base-pasteque', name: 'Pastèque', brand: '', calories: 30, proteines: 0.6, glucides: 7, lipides: 0.2, image_url: null },
  { code: 'base-ananas', name: 'Ananas', brand: '', calories: 50, proteines: 0.5, glucides: 12, lipides: 0.1, image_url: null },
  { code: 'base-kiwi', name: 'Kiwi', brand: '', calories: 58, proteines: 1, glucides: 12, lipides: 0.4, image_url: null },
  { code: 'base-mangue', name: 'Mangue', brand: '', calories: 63, proteines: 0.6, glucides: 14, lipides: 0.3, image_url: null },
  { code: 'base-figue', name: 'Figue', brand: '', calories: 70, proteines: 0.7, glucides: 16, lipides: 0.3, image_url: null },
  { code: 'base-grenade', name: 'Grenade', brand: '', calories: 75, proteines: 1.7, glucides: 16, lipides: 1.2, image_url: null },
  { code: 'base-avocat', name: 'Avocat', brand: '', calories: 160, proteines: 2, glucides: 1.8, lipides: 15, image_url: null },
  { code: 'base-dattes', name: 'Dattes séchées', brand: '', calories: 282, proteines: 2.5, glucides: 64, lipides: 0.4, image_url: null },

  // ===== LEGUMES =====
  { code: 'base-tomate', name: 'Tomate', brand: '', calories: 20, proteines: 0.8, glucides: 3.5, lipides: 0.3, image_url: null },
  { code: 'base-courgette', name: 'Courgette', brand: '', calories: 17, proteines: 1.2, glucides: 2, lipides: 0.3, image_url: null },
  { code: 'base-aubergine', name: 'Aubergine', brand: '', calories: 18, proteines: 1, glucides: 2, lipides: 0.2, image_url: null },
  { code: 'base-poivron', name: 'Poivron', brand: '', calories: 27, proteines: 0.9, glucides: 5, lipides: 0.2, image_url: null },
  { code: 'base-brocoli', name: 'Brocoli', brand: '', calories: 34, proteines: 3, glucides: 4, lipides: 0.4, image_url: null },
  { code: 'base-chou-fleur', name: 'Chou-fleur', brand: '', calories: 22, proteines: 1.9, glucides: 2.5, lipides: 0.4, image_url: null },
  { code: 'base-carotte', name: 'Carotte', brand: '', calories: 36, proteines: 0.8, glucides: 7, lipides: 0.2, image_url: null },
  { code: 'base-haricots-verts', name: 'Haricots verts', brand: '', calories: 30, proteines: 1.8, glucides: 4.5, lipides: 0.2, image_url: null },
  { code: 'base-epinards', name: 'Épinards', brand: '', calories: 23, proteines: 2.9, glucides: 1.6, lipides: 0.4, image_url: null },
  { code: 'base-champignons', name: 'Champignons', brand: '', calories: 25, proteines: 2.5, glucides: 2.3, lipides: 0.3, image_url: null },
  { code: 'base-salade-verte', name: 'Salade verte', brand: '', calories: 14, proteines: 1.3, glucides: 1.5, lipides: 0.2, image_url: null },
  { code: 'base-roquette', name: 'Roquette', brand: '', calories: 25, proteines: 2.6, glucides: 2, lipides: 0.5, image_url: null },
  { code: 'base-endive', name: 'Endive', brand: '', calories: 18, proteines: 0.8, glucides: 2.5, lipides: 0.2, image_url: null },
  { code: 'base-concombre', name: 'Concombre', brand: '', calories: 12, proteines: 0.6, glucides: 1.8, lipides: 0.1, image_url: null },
  { code: 'base-radis', name: 'Radis', brand: '', calories: 16, proteines: 0.7, glucides: 2.5, lipides: 0.1, image_url: null },
  { code: 'base-betterave', name: 'Betterave (cuite)', brand: '', calories: 38, proteines: 1.6, glucides: 7, lipides: 0.2, image_url: null },
  { code: 'base-poireau', name: 'Poireau (cuit)', brand: '', calories: 30, proteines: 1.5, glucides: 5, lipides: 0.3, image_url: null },
  { code: 'base-fenouil', name: 'Fenouil', brand: '', calories: 24, proteines: 1.2, glucides: 4, lipides: 0.2, image_url: null },
  { code: 'base-celeri-rave', name: 'Céleri-rave', brand: '', calories: 25, proteines: 1.5, glucides: 3, lipides: 0.3, image_url: null },
  { code: 'base-asperges', name: 'Asperges', brand: '', calories: 23, proteines: 2.2, glucides: 2, lipides: 0.2, image_url: null },
  { code: 'base-artichaut', name: 'Artichaut (cuit)', brand: '', calories: 50, proteines: 3.3, glucides: 6, lipides: 0.3, image_url: null },
  { code: 'base-potiron', name: 'Potiron', brand: '', calories: 26, proteines: 1, glucides: 5, lipides: 0.1, image_url: null },
  { code: 'base-oignon', name: 'Oignon', brand: '', calories: 40, proteines: 1.1, glucides: 8, lipides: 0.1, image_url: null },

  // ===== PLATS PREPARES =====
  { code: 'base-pates-carbonara', name: 'Pâtes à la carbonara', brand: '', calories: 200, proteines: 7, glucides: 25, lipides: 8, image_url: null },
  { code: 'base-pates-bolognaise', name: 'Pâtes à la bolognaise', brand: '', calories: 130, proteines: 6, glucides: 17, lipides: 4, image_url: null },
  { code: 'base-lasagnes', name: 'Lasagnes', brand: '', calories: 145, proteines: 7, glucides: 14, lipides: 6, image_url: null },
  { code: 'base-quiche-lorraine', name: 'Quiche lorraine', brand: '', calories: 295, proteines: 11, glucides: 22, lipides: 19, image_url: null },
  { code: 'base-pizza-margherita', name: 'Pizza Margherita', brand: '', calories: 245, proteines: 11, glucides: 30, lipides: 9, image_url: null },
  { code: 'base-pizza-4-fromages', name: 'Pizza 4 fromages', brand: '', calories: 280, proteines: 13, glucides: 28, lipides: 13, image_url: null },
  { code: 'base-hamburger', name: 'Hamburger', brand: '', calories: 290, proteines: 14, glucides: 25, lipides: 15, image_url: null },
  { code: 'base-sandwich-jb', name: 'Sandwich jambon-beurre', brand: '', calories: 290, proteines: 11, glucides: 35, lipides: 11, image_url: null },
  { code: 'base-taboule', name: 'Taboulé', brand: '', calories: 165, proteines: 4, glucides: 28, lipides: 4, image_url: null },
  { code: 'base-couscous', name: 'Couscous au poulet', brand: '', calories: 130, proteines: 6, glucides: 17, lipides: 3.5, image_url: null },
  { code: 'base-hachis-parmentier', name: 'Hachis parmentier', brand: '', calories: 130, proteines: 7, glucides: 13, lipides: 5, image_url: null },
  { code: 'base-sushi', name: 'Sushi (assortiment)', brand: '', calories: 150, proteines: 6, glucides: 28, lipides: 1.5, image_url: null },

  // ===== SNACKS & DESSERTS =====
  { code: 'base-chips', name: 'Chips', brand: '', calories: 535, proteines: 6, glucides: 51, lipides: 33, image_url: null },
  { code: 'base-frites', name: 'Frites', brand: '', calories: 280, proteines: 4, glucides: 35, lipides: 14, image_url: null },
  { code: 'base-popcorn', name: 'Pop-corn sucré', brand: '', calories: 425, proteines: 7, glucides: 75, lipides: 12, image_url: null },
  { code: 'base-cookies', name: 'Cookies', brand: '', calories: 480, proteines: 6, glucides: 65, lipides: 22, image_url: null },
  { code: 'base-petit-beurre', name: 'Biscuits petit-beurre', brand: '', calories: 440, proteines: 7, glucides: 70, lipides: 14, image_url: null },
  { code: 'base-madeleine', name: 'Madeleine', brand: '', calories: 425, proteines: 6, glucides: 50, lipides: 22, image_url: null },
  { code: 'base-glace-vanille', name: 'Glace vanille', brand: '', calories: 195, proteines: 3, glucides: 24, lipides: 10, image_url: null },
  { code: 'base-glace-chocolat', name: 'Glace chocolat', brand: '', calories: 215, proteines: 4, glucides: 27, lipides: 11, image_url: null },
  { code: 'base-tarte-pomme', name: 'Tarte aux pommes', brand: '', calories: 260, proteines: 3, glucides: 38, lipides: 11, image_url: null },

  // ===== BOISSONS =====
  { code: 'base-cafe-noir', name: 'Café noir', brand: '', calories: 2, proteines: 0.1, glucides: 0, lipides: 0, image_url: null },
  { code: 'base-cafe-au-lait', name: 'Café au lait', brand: '', calories: 30, proteines: 1.5, glucides: 2.5, lipides: 1.5, image_url: null },
  { code: 'base-the-noir', name: 'Thé noir', brand: '', calories: 1, proteines: 0, glucides: 0, lipides: 0, image_url: null },
  { code: 'base-the-vert', name: 'Thé vert', brand: '', calories: 1, proteines: 0, glucides: 0, lipides: 0, image_url: null },
  { code: 'base-jus-orange', name: 'Jus d\'orange', brand: '', calories: 45, proteines: 0.7, glucides: 10, lipides: 0.2, image_url: null },
  { code: 'base-jus-pomme', name: 'Jus de pomme', brand: '', calories: 47, proteines: 0.1, glucides: 11, lipides: 0.1, image_url: null },
  { code: 'base-coca', name: 'Coca-Cola', brand: '', calories: 42, proteines: 0, glucides: 10.6, lipides: 0, image_url: null },
  { code: 'base-eau-gazeuse', name: 'Eau gazeuse', brand: '', calories: 0, proteines: 0, glucides: 0, lipides: 0, image_url: null },

  // ===== MATIERES GRASSES & OLEAGINEUX =====
  { code: 'base-huile-olive', name: 'Huile d\'olive', brand: '', calories: 900, proteines: 0, glucides: 0, lipides: 100, image_url: null },
  { code: 'base-huile-colza', name: 'Huile de colza', brand: '', calories: 900, proteines: 0, glucides: 0, lipides: 100, image_url: null },
  { code: 'base-amandes', name: 'Amandes', brand: '', calories: 578, proteines: 21, glucides: 7, lipides: 50, image_url: null },
  { code: 'base-noix', name: 'Noix', brand: '', calories: 654, proteines: 15, glucides: 7, lipides: 63, image_url: null },
  { code: 'base-noisettes', name: 'Noisettes', brand: '', calories: 630, proteines: 15, glucides: 11, lipides: 60, image_url: null },
  { code: 'base-cacahuetes', name: 'Cacahuètes', brand: '', calories: 570, proteines: 25, glucides: 14, lipides: 49, image_url: null },
  { code: 'base-graines-chia', name: 'Graines de chia', brand: '', calories: 480, proteines: 17, glucides: 8, lipides: 31, image_url: null },
  { code: 'base-graines-courge', name: 'Graines de courge', brand: '', calories: 560, proteines: 30, glucides: 13, lipides: 49, image_url: null },
  { code: 'base-beurre-cacahuete', name: 'Beurre de cacahuète', brand: '', calories: 588, proteines: 25, glucides: 14, lipides: 50, image_url: null },

  // ===== CONDIMENTS =====
  { code: 'base-mayonnaise', name: 'Mayonnaise', brand: '', calories: 700, proteines: 1, glucides: 1, lipides: 78, image_url: null },
  { code: 'base-ketchup', name: 'Ketchup', brand: '', calories: 100, proteines: 1, glucides: 23, lipides: 0.2, image_url: null },
  { code: 'base-moutarde', name: 'Moutarde', brand: '', calories: 100, proteines: 6, glucides: 4, lipides: 6, image_url: null },
  { code: 'base-vinaigrette', name: 'Vinaigrette', brand: '', calories: 380, proteines: 0.5, glucides: 7, lipides: 38, image_url: null },
  { code: 'base-sauce-tomate', name: 'Sauce tomate', brand: '', calories: 60, proteines: 1.5, glucides: 9, lipides: 2, image_url: null },

  // ===== SUCRES & PATES A TARTINER =====
  { code: 'base-miel', name: 'Miel', brand: '', calories: 320, proteines: 0.4, glucides: 78, lipides: 0, image_url: null },
  { code: 'base-confiture', name: 'Confiture (fraise)', brand: '', calories: 270, proteines: 0.5, glucides: 65, lipides: 0.1, image_url: null },
  { code: 'base-nutella', name: 'Pâte à tartiner (Nutella)', brand: '', calories: 540, proteines: 6, glucides: 56, lipides: 31, image_url: null },
  { code: 'base-sirop-erable', name: 'Sirop d\'érable', brand: '', calories: 260, proteines: 0, glucides: 67, lipides: 0, image_url: null },
  { code: 'base-sucre', name: 'Sucre', brand: '', calories: 400, proteines: 0, glucides: 100, lipides: 0, image_url: null },
  { code: 'base-chocolat-noir', name: 'Chocolat noir 70%', brand: '', calories: 545, proteines: 8, glucides: 33, lipides: 41, image_url: null },
  { code: 'base-chocolat-lait', name: 'Chocolat au lait', brand: '', calories: 535, proteines: 7, glucides: 55, lipides: 32, image_url: null },

  // ===== AUTRES =====
  { code: 'base-whey', name: 'Whey protéine', brand: '', calories: 380, proteines: 75, glucides: 8, lipides: 5, image_url: null },
];

/**
 * Recherche dans la base d'aliments courants
 */
export function searchAlimentsBase(query: string): NutritionData[] {
  const words = query.toLowerCase().split(/\s+/);
  return ALIMENTS_BASE.filter((a) => {
    const name = a.name.toLowerCase();
    return words.every((word) => name.includes(word));
  });
}
